const getLocationOptions = () => {
    return [
      "Nigeria",
      "Romania",
      "Indonesia",
      "Thailand",
      "Mexico",
      "Australia",
      "Argentina",
      "Ireland",
      "Germany",
      "Russia",
      "India",
      "China",
      "Türkiye",
      "Tanzania",
      "Japan",
      "Iraq",
      "Morocco",
      "Madagascar",
      "South Korea",
      "Philippines",
      "Israel",
      "Brazil",
      "Cuba",
      "Afghanistan",
      "Egypt",
      "Senegal",
      "Botswana",
      "Vietnam",
      "Kazakhstan",
      "Mongolia",
      "Bulgaria",
      "Iceland",
      "Spain",
      "France",
      "Poland",
      "Colombia",
      "Georgia",
      "Italy",
      "Peru",
      "Norway",
      "El Salvador",
      "Myanmar",
      // Add more locations as needed
    ];
  };

export default getLocationOptions;
